# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('v2x-lte-cell', ['v2x-lte', 'flow-monitor'])
    obj.source = 'v2x-lte-cell.cc'

